use_frameworks!

platform :ios, '8.0'

target 'Rudder-Amplitude_Example' do
  pod 'Rudder-Amplitude', :path => '../'

  target 'Rudder-Amplitude_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
